Phone.create(name: "Stromberg Carlson", model: "500 Rotary Desk Telephone", vintage: "1940-69")
Phone.create(name: "Kellogg/ITT", model: "554 Rotary Wall Telephone", vintage: "1940-69")
Phone.create(name: "Northern Telecom", model: "500 Rotary Desk Telephone", vintage: "1970-present")
Phone.create(name: "AT&T", model: "500 Rotary Desk Telephone", vintage: "1970-present")
Phone.create(name: "Western Electric", model: "302 Rotary Desk Telephone", vintage: "1940-69")